Ajout des modèles de base de l'application
Lern-PFR/lern-api pull request #3
Opened 2021-04-30 15:34 UTC by yannhodiesne

Ajout des modèles de base et des annotations utiles à l'affichage au sein de Swagger
Les différents modèles n'apparaitront dans Swagger qu'une fois qu'ils seront utilisés par les routes de l'API

> !! Cette PR nécessite une remise à zéro d'une éventuelle base de données existante (`docker-compose down -v`)

2021-05-11 15:41 UTC, simonfranza commented on .run/docker-compose.run.xml
> +  <configuration default="false" name="docker-compose" type="docker-deploy" factoryName="docker-compose.yml" server-name="Docker">
Question peut-être stupide, mais ça serait pas logique de spécifier `default="true"` ici ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/AnswerRequest.cs
> +        [Required, MinLength(3), MaxLength(300)]
Sûrement du chipotage, mais ce serait pas plus clean de déclarer les valeur min et max pour la longueur dans une constante, histoire de pouvoir tout changer en une seule fois au besoin ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/ArticleRequest.cs
> +        public Guid ConceptId { get; set; }
Concept correspond à "Notion" ou à autre chose ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/ConceptRequest.cs
> +        public int Order { get; set; }
Ce serait pas plus opti d'utiliser une liste chaînée plutôt qu'un index d'ordre ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/ConceptRequest.cs
> +    [ExcludeFromCodeCoverage]
Pourquoi exclure spécifiquement ce Validator et pas ceux des fichiers précédents ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/CourseRequest.cs
> +        public int Order { get; set; }
Ce serait pas plus opti d'utiliser une liste chaînée plutôt qu'un index d'ordre ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/ExerciseRequest.cs
> +        public int Order { get; set; }
Ce serait pas plus opti d'utiliser une liste chaînée plutôt qu'un index d'ordre ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/ModuleRequest.cs
> +        public int Order { get; set; }
Ce serait pas plus opti d'utiliser une liste chaînée plutôt qu'un index d'ordre ?

2021-05-11 15:41 UTC, once-upon-a-tam commented on Lern-API/DataTransferObjects/Requests/QuestionRequest.cs
> +            RuleFor(x => x.Answers).NotEmpty();
Il existe pas une méthode pour s'assurer que la liste de réponse ne contienne que des données enregistrées en base ?

2021-05-11 15:41 UTC, simonfranza commented on Lern-API/DataTransferObjects/Requests/UserRequest.cs
> +                RuleFor(x => x.Password).Length(8, 100).Unless(p => p == null);
L'ajout de la clause `Unless` correspond à la logique d'email de génération de mot de passe, c'est ça ?

2021-05-11 15:41 UTC, simonfranza commented on Lern-API/Helpers/Validation/ValidationExtensions.cs
> +            return rule.MustAsync(async (_, id, token) => await service.Exists(id, token)).WithMessage($"Given {typeof(T).Name} does not exist");
`provided` plutôt que `given` ici, non ?

2021-05-11 15:41 UTC, simonfranza commented on Lern-API/Helpers/Validation/ValidationExtensions.cs
> +            }).WithMessage($"Given {typeof(T).Name} does not exist");
`provided` plutôt que `given` ici, non ?

2021-05-11 16:21 UTC, simonfranza commented on Lern-API/DataTransferObjects/Requests/QuestionRequest.cs
> +        public string Explanation { get; set; }
L'explication n'est pas requise, c'est au bon vouloir de l'auteur

2021-05-11 18:15 UTC, frenchykiller requested changes

2021-05-11 18:15 UTC, frenchykiller commented on Lern-API/DataTransferObjects/Requests/ConceptRequest.cs
> +    [ExcludeFromCodeCoverage]
Sont exclus:
- ConceptRequestValidator
- CourseRequestValidator
- ExerciseRequestValidator
- ModuleRequestValidator
Ne sont pas exclus:
- AnswerRequestValidator
- SubjectRequestValidator
- QuestionRequestValidator

Ça m'a l'air d'être un oubli sur les 3 plutôt qu'un ajout sur les autres?

2021-05-12 13:48 UTC, yannhodiesne commented on .run/docker-compose.run.xml
> +  <configuration default="false" name="docker-compose" type="docker-deploy" factoryName="docker-compose.yml" server-name="Docker">
Je sais honnêtement pas ce que ça changerait, c'est un fichier généré par Rider
Je préfère pas y toucher

2021-05-12 13:49 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/AnswerRequest.cs
> +        [Required, MinLength(3), MaxLength(300)]
A faire dans une PR à part, après une réunion où on passe en revue les valeurs à affecter
(https://trello.com/c/ilWUdEk2/49-as-a-developer-i-want-the-api-to-have-constants-defining-the-max-length-of-every-field)

2021-05-12 13:50 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/ArticleRequest.cs
> +        public Guid ConceptId { get; set; }
c'est ça

2021-05-12 13:51 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/ConceptRequest.cs
> +        public int Order { get; set; }
Pas au niveau base de données, ça serait juste un bordel de clés étrangères très compliqué à gérer

2021-05-12 13:51 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/ExerciseRequest.cs
> +        public int Order { get; set; }
Pas au niveau base de données, ça serait juste un bordel de clés étrangères très compliqué à gérer

2021-05-12 13:51 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/ModuleRequest.cs
> +        public int Order { get; set; }
Pas au niveau base de données, ça serait juste un bordel de clés étrangères très compliqué à gérer

2021-05-12 13:52 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/QuestionRequest.cs
> +            RuleFor(x => x.Answers).NotEmpty();
Si, mais le but de ce DTO est de laisser la possibilité de créer/supprimer des réponses à la volée sans passer par une autre route à appeler une fois par réponse

2021-05-12 13:53 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/UserRequest.cs
> +                RuleFor(x => x.Password).Length(8, 100).Unless(p => p == null);
Non, la clause unless permet de laisser la possibilité d'omettre totalement le mot de passe lors d'un `PUT /api/user/:id` afin de garder celui qui est déjà en BDD

2021-05-12 13:55 UTC, yannhodiesne commented on Lern-API/DataTransferObjects/Requests/CourseRequest.cs
> +        public int Order { get; set; }
Pas au niveau base de données, ça serait juste un bordel de clés étrangères très compliqué à gérer

2021-05-12 14:27 UTC, frenchykiller approved these changes

2021-05-12 14:31 UTC, simonfranza approved these changes

2021-05-12 14:32 UTC, merged